apiVersion: v1
kind: Service
metadata:
  name: {{ include "ui-runner-smoke-0505.name" . }}
  labels:
    {{- include "ui-runner-smoke-0505.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "ui-runner-smoke-0505.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
